server:
  port: 8085

spring:
  main:
    allow-bean-definition-overriding: true


keycloak:
  # turn off keycloak spring boot auto-configuration:
  # We only want to use Spring Security without servlet container specific infrastructure
  # This allows us to pull the Keycloak configuration from here instead of keycloak.json
  enabled: false

  realm: dev
  auth-server-url: http://localhost:8080/auth
  # The client_id
  resource: employee-service
  credentials:
    # The client_secret
    secret: d3316306-9722-4126-8411-d1af88ee5a17
  ssl-required: external
  # Configures what principal.getName() will return
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  token-minimum-time-to-live: 30